const ProjectsData = [
    {
        name : "#PeduliCOVID-19",
        description : "Site about COVID-19 Pandemic informations, suggestion and history.",
        image : "../images/pedulicovid19.png",
        visit : "https://arifian853.github.io/pedulicovid-19/",
        repo : "https://github.com/arifian853/pedulicovid-19",
    },
    {
        name : "#PeduliCOVID-19 Flask",
        description : "Site about COVID-19 Pandemic informations, suggestion and history. But with Flask backend",
        image : "../images/pedulicovid19.png",
        visit : "https://www.google.com/search?q=NOT+FOUND",
        repo : "https://github.com/arifian853/pedulicovid-19-flask",
    },
    {
        name : "MovieInfo.com",
        description : "This site contains movie lists from The Movie Database (TMDB) API.",
        image : "../images/movie-info.png",
        visit : "https://arifian853.github.io/GDSC-movie-info/",
        repo : "https://github.com/arifian853/GDSC-movie-info",
    },
    {
        name : "Simple Weather App",
        description : "A simple weather forecast app made with React JS and API integrating",
        image : "../images/weatherapp.png",
        visit : "https://arifian853.github.io/simple-weather-app/",
        repo : "https://github.com/arifian853/simple-weather-app",
    },
    {
        name : "API-RMU",
        description : "API for Room Usage Monitoring app at Faculty of Engineering (Software Development Project), reserve method to connect to database.",
        image : "../images/api-rmu.png",
        visit : "https://github.com/arifian853/RMU-API-Project-v1.0.2",
        repo : "https://gitlab.com/tekad-matulatan/api-rmu",
    },
    {
        name : "LoginAuth (Edge />)",
        description : "React App frontend for registering an account and login an account.(API not deployed)",
        image : "../images/loginauth.png",
        visit : "https://arifian853.github.io/loginAuth-frontend-build",
        repo : "https://github.com/arifian853/loginAuth-frontend",
    },
    {
        name : "Bring Back The Nature",
        description : "Simple survival game made with Unity3D Engine.",
        image : "../images/bbtn.png",
        visit : "https://drive.google.com/drive/folders/1P0Cy4KdjiF9cXpwTo05E8zn5nzsbrB8m",
        repo : "https://github.com/arifian853/BringBackTheNature",
    },
    {
        name : "Bookshelf App",
        description : "Simple Bookshelf App with HTML,CSS,JavaScript with localStorage functionality and DOM manipulation.",
        image : "../images/bookshelf.png",
        visit : "https://arifian853.github.io/bookshelf-app-js/",
        repo : "https://github.com/arifian853/bookshelf-app-js",
    },
    {
        name : "CariFilm",
        description : "Web for searching film titles with TMDB API and Webpack Environment.",
        image : "../images/carifilm.png",
        visit : "https://arifian853.github.io/CariFilm/",
        repo : "https://github.com/arifian853/CariFilm-Webpack",
    },
    {
        name : "My Notes",
        description : "Simple Notes app using State dan Props",
        image : "../images/notes.png",
        visit : "https://my-notes-react.vercel.app/",
        repo : "https://github.com/arifian853/my-notes-react",
    },
    {
        name : "MakanCuy App",
        description : "Restaurant Catalogue Progressive Web App (PWA) named MakanCuy. Made with webpack environment.",
        image : "../images/makancuy.png",
        visit : "https://makancuy-finals.netlify.app/",
        repo : "https://github.com/arifian853/pwa-restaurant-catalog",
    },
    {
        name : "Herbal.in",
        description : "Web Application for buying herbal medicines",
        image : "../images/herbalin.png",
        visit : "https://herbal-in.vercel.app/",
        repo : "https://github.com/arifian853/Herbal.in",
    },
    {
        name : "Desa Wisata Pengudang",
        description : "Web for Pengudang Tourism Village, focusing on how tourist can know more about Pengudang. ",
        image : "../images/pengudang.png",
        visit : "https://pengudangbintanmangrove.id/",
        repo : "https://www.google.com/search?q=NOT+FOUND",
    },
];

export default ProjectsData;